### ISSUE TITLE
Terraform in Action ch4

### ISSUE THREAD

**Issue by angrypapa** [scottwinkler/terraform-vanilla-webserver-DEPRECATED#1]
Hi. Do you actually have the terraform files for ch4 of the book available anywhere? I tried what's on the book, it doesn't work. Since there's a lot of things you don't explain there it's a pain to understand why. Any help?

**Comment by scottwinkler** [comment]
Hi,
I moved all the code into the terraform-in-action organization. Here you can find it:

https://github.com/terraform-in-action/manning-code

And here is the non-deprecated version of the repo you are looking at currently:
https://github.com/scottwinkler/vanilla-webserver-src (still need to move this to terraform-in-action org but can't do it until i update chapter 4 code)

**Comment by angrypapa** [comment]
Thank you.
